import { Schema, model, Document, Types } from "mongoose";
import { UserModel } from "./userModel";

export interface SalarySlipEarnings {
  basic: number;
  hra: number;
  mobileReimbursement: number;
  booksReimbursement: number;
  specialAllowances: number;
  incentives: number;
  total: number;
}

export interface SalarySlipDeductions {
  pf: number;
  professionalTax: number;
  tds: number;
  otherDeductions: number;
  lopDeduction: number;
  total: number;
}

export interface SalarySlipLeaveBreakdown {
  // YTD figures — retained for back-compat with already-generated slips.
  // The printable slip no longer surfaces them prominently to avoid
  // the "8 yearly available, employee assumes no LOP" confusion.
  paidAccrued: number;
  paidUsed: number;
  paidBalance: number;
  medicalAccrued: number;
  medicalUsed: number;
  medicalBalance: number;
  // ── This-month-only figures ──
  // What the employee is ENTITLED to and USED in the payroll period.
  // The renderer prefers these when present. Optional so reads of
  // legacy slips don't break.
  paidMonthlyQuota?: number;
  paidUsedThisMonth?: number;
  medicalMonthlyQuota?: number;
  medicalUsedThisMonth?: number;
  unpaidDays: number;
  bonusPaid: number;
  bonusMedical: number;
}

export interface SalarySlipDoc extends Document {
  _id: Types.ObjectId;
  user: Types.ObjectId;
  year: number;
  month: number;
  employeeName: string;
  employeeId: string;
  designation: string;
  dateOfJoining?: Date;
  country: "IN" | "US";
  currency: "INR" | "USD";
  totalDays: number;
  weekendDays: number;
  holidays: number;
  workingDays: number;
  presentDays: number;
  earnings: SalarySlipEarnings;
  deductions: SalarySlipDeductions;
  leaves: SalarySlipLeaveBreakdown;
  perDayRate: number;
  netPay: number;
  netPayWords: string;
  generatedAt: Date;
  generatedBy?: Types.ObjectId;
  // ── Publish gate ──
  // Generated slips are HR-internal until explicitly published. Employee
  // endpoints (`getMySlip` / `getMySlipsList`) filter on this so an
  // employee never sees a draft slip mid-payroll-review. Re-running
  // generation for an already-published month preserves the `published`
  // flag — HR can republish overrides without re-confirming visibility.
  published: boolean;
  publishedAt?: Date;
  publishedBy?: Types.ObjectId;
  createdAt: Date;
  updatedAt: Date;
}

const slipSchema = new Schema<SalarySlipDoc>(
  {
    user: { required: true, type: Schema.Types.ObjectId, ref: UserModel },
    year: { type: Number, required: true },
    month: { type: Number, required: true, min: 1, max: 12 },
    employeeName: { type: String, default: "" },
    employeeId: { type: String, default: "" },
    designation: { type: String, default: "" },
    dateOfJoining: { type: Date },
    country: { type: String, enum: ["IN", "US"], default: "IN" },
    currency: { type: String, enum: ["INR", "USD"], default: "INR" },
    totalDays: { type: Number, default: 0 },
    weekendDays: { type: Number, default: 0 },
    holidays: { type: Number, default: 0 },
    workingDays: { type: Number, default: 0 },
    presentDays: { type: Number, default: 0 },
    earnings: {
      basic: { type: Number, default: 0 },
      hra: { type: Number, default: 0 },
      mobileReimbursement: { type: Number, default: 0 },
      booksReimbursement: { type: Number, default: 0 },
      specialAllowances: { type: Number, default: 0 },
      incentives: { type: Number, default: 0 },
      total: { type: Number, default: 0 },
    },
    deductions: {
      pf: { type: Number, default: 0 },
      // Default 0 on slips (not 208) so already-generated legacy slips
      // don't retroactively claim a PT deduction that wasn't in their
      // stored total. New slips generated by salaryCalculationService
      // populate this with 208 (or config-supplied override).
      professionalTax: { type: Number, default: 0 },
      tds: { type: Number, default: 0 },
      otherDeductions: { type: Number, default: 0 },
      lopDeduction: { type: Number, default: 0 },
      total: { type: Number, default: 0 },
    },
    leaves: {
      // YTD figures — back-compat for legacy slips. Not surfaced on
      // the printable slip anymore.
      paidAccrued: { type: Number, default: 0 },
      paidUsed: { type: Number, default: 0 },
      paidBalance: { type: Number, default: 0 },
      medicalAccrued: { type: Number, default: 0 },
      medicalUsed: { type: Number, default: 0 },
      medicalBalance: { type: Number, default: 0 },
      // ── This-month figures ──
      paidMonthlyQuota: { type: Number, default: 0 },
      paidUsedThisMonth: { type: Number, default: 0 },
      medicalMonthlyQuota: { type: Number, default: 0 },
      medicalUsedThisMonth: { type: Number, default: 0 },
      unpaidDays: { type: Number, default: 0 },
      bonusPaid: { type: Number, default: 0 },
      bonusMedical: { type: Number, default: 0 },
    },
    perDayRate: { type: Number, default: 0 },
    netPay: { type: Number, default: 0 },
    netPayWords: { type: String, default: "" },
    generatedAt: { type: Date, default: Date.now },
    generatedBy: { type: Schema.Types.ObjectId, ref: UserModel },
    // Publish gate — see interface comment above. Defaults false so a
    // freshly generated slip is invisible to the employee until HR
    // clicks Publish on the admin page.
    published: { type: Boolean, default: false, index: true },
    publishedAt: { type: Date },
    publishedBy: { type: Schema.Types.ObjectId, ref: UserModel },
  },
  { timestamps: true },
);

slipSchema.index({ user: 1, year: 1, month: 1 }, { unique: true });
slipSchema.index({ year: 1, month: 1 });

export const SalarySlipModel = model<SalarySlipDoc>(
  "SalarySlip",
  slipSchema,
);
